network:
  version: 2
  renderer: networkd
  ethernets:
    ens34:
      addresses:
        - 192.168.16.32/24
      routes:
        - to: default
          via: 192.168.16.1
      nameservers:
          addresses: [8.8.8.8, 1.1.1.1]